# Fly.io configuration - Alternative to Render
app = "cryptouniverse-backend"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile.render"

[env]
  PORT = "8080"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
