# Render deployment configuration for CryptoUniverse Enterprise
services:
  # Backend API Service
  - type: web
    name: cryptouniverse-backend
    runtime: python
    plan: pro  # Professional tier for production workload
    region: oregon  # Choose region closest to your users
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cryptouniverse-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cryptouniverse-redis
          property: connectionString
      - key: CORS_ORIGINS
        value: https://cryptouniverse-frontend.onrender.com
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: WORKERS
        value: 4
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /api/v1/status
    autoDeploy: true
    
  # Redis Cache Service
  - type: redis
    name: cryptouniverse-redis
    plan: pro  # Professional Redis instance
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []  # Allow access from backend service
    
  # Background Worker Service (for autonomous trading)
  - type: worker
    name: cryptouniverse-worker
    runtime: python
    plan: pro
    region: oregon
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python -m app.services.background_worker
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cryptouniverse-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cryptouniverse-redis
          property: connectionString
      - key: WORKER_TYPE
        value: autonomous_trading
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: cryptouniverse-db
    plan: pro  # Professional database tier
    region: oregon
    databaseName: cryptouniverse
    user: cryptouniverse
    postgresMajorVersion: 15

# Static Site Configuration (Frontend)
# Note: This will be configured separately in Render dashboard
# or via separate render-frontend.yaml